language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=25
 - ANDROID_BUILD_TOOLS=25.0.2

android:
   components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository

   licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    ./gradlew build
